_BASE_: Base-PanopticDeepLab-OS16.yaml
MODEL:
  WEIGHTS: "./pretrained/x65.pkl"
  PIXEL_MEAN: [128, 128, 128]
  PIXEL_STD: [128, 128, 128]
  BACKBONE:
    NAME: "d2_xception_65"
  RESNETS:
    NORM: "SyncBN"
    RES4_DILATION: 1
    RES5_DILATION: 2
SOLVER:
  MAX_ITER: 90000
INPUT:
  FORMAT: "RGB"
  CROP:
    ENABLED: True # pool_kernel_size
    SIZE: (1024, 2048)
OUTPUT_DIR: "./xception65_61218/"