_BASE_: Base-PanopticDeepLab-OS16_369.yaml
MODEL:
  WEIGHTS: "./pretrained/x65.pkl"
  PIXEL_MEAN: [128, 128, 128]
  PIXEL_STD: [128, 128, 128]
  BACKBONE:
    NAME: "d2_xception_65"
  RESNETS:
    NORM: "BN" #SyncBN
    RES4_DILATION: 1
    RES5_DILATION: 2
SOLVER:
  MAX_ITER: 90000
  IMS_PER_BATCH: 1
INPUT:
  FORMAT: "RGB"
  CROP:
    ENABLED: False # pool_kernel_size
    SIZE: (1024, 2048)
OUTPUT_DIR: "./output/xception65_369/"
DATALOADER:
  NUM_WORKERS: 2