_BASE_: Base-PanopticDeepLab-OS16.yaml
MODEL:
  WEIGHTS: "./pretrained/x65.pkl"
  PIXEL_MEAN: [128, 128, 128]
  PIXEL_STD: [128, 128, 128]
  BACKBONE:
    NAME: "d2_xception_65"
  RESNETS:
    NORM: "BN" #SyncBN: Multi-GPU
    RES4_DILATION: 1
    RES5_DILATION: 2
  PANOPTIC_DEEPLAB:
    USE_DEPTHWISE_SEPARABLE_CONV: True
  SEM_SEG_HEAD:
    USE_DEPTHWISE_SEPARABLE_CONV: True
SOLVER:
  OPTIMIZER: "ADAM"
  BASE_LR: 0.00005
  WEIGHT_DECAY: 0.0
  WEIGHT_DECAY_NORM: 0.0
  WEIGHT_DECAY_BIAS: 0.0
  MAX_ITER: 60000
  LR_SCHEDULER_NAME: "WarmupPolyLR"
  IMS_PER_BATCH: 8
INPUT:
  FORMAT: "RGB"
  CROP:
    ENABLED: True
    TYPE: "absolute"
    SIZE: (513, 1025)
OUTPUT_DIR: "./output/xception65_dsconv_61218_lr5e-5/"
DATALOADER:
  NUM_WORKERS: 1